spring:
  application:
    name: bend-his-insurance-application
  thymeleaf:
    cache: false
server:
  port: 8082
  tomcat:
    uri-encoding: utf-8

swagger:
  enable: true
  title: 医保接口嵌入式系统
  description: 医保接口嵌入式系统
  version: 1.0.0
  base-package: com.bend.his.insurance.application.controller

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus
    metrics:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
    hibernate: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%C{1}:%L] : %m%n'
debug: true
