spring:
  application:
    name: bend-his-insurance-impl  # 设置值保证程序启动时不报错
  datasource:
    url: jdbc:mysql://mysql.liudebin.cn:13306/his_insurance?useUnicode=true&amp;characterEncoding=utf8mb4&amp;useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: fbmgr@#
    type: com.alibaba.druid.pool.DruidDataSource

## mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bend.his.insurance.biz.dataobject
  executor-type: reuse
  configuration:
    # 全局映射器启用缓存
    cache-enabled: true
    # 当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载。
    aggressive-lazy-loading: false
    # 全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
    lazy-loading-enabled: false
    # 对于批量更新操作缓存SQL以提高性能
    default-executor-type: reuse
    # 允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    # 数据库执行超时时间
    default-statement-timeout: 25000
    # 打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 允许 JDBC 支持自动生成主键，需要驱动兼容。 如果设置为 true 则这个设置强制使用自动生成主键
    use-generated-keys: true
    # 设置但JDBC类型为空时,某些驱动程序 要指定值,default:OTHER，插入空值时不需要指定类型
    jdbc-type-for-null: null
    # 使用驼峰命名法转换字段
    map-underscore-to-camel-case: true
    # 指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射　PARTIAL:部分  FULL:全部
    auto-mapping-behavior: partial
    # 是否可以使用列的别名 (取决于驱动的兼容性) default:true
    use-column-label: true
    # 指定 Mybatis 创建具有延迟加载能力的对象所用到的代理工具。CGLIB|JAVASSIST, default(JAVASSIST)
#    proxy-factory: CGLIB
    # 指定 MyBatis 增加到日志名称的前缀。任何字符串
    log-prefix: test


# logging
logging:
  level:
    # dao 开启 debug 模式 mybatis 输入 sql
    com.bend.his.insurance.biz.dao: debug
#
pagehelper:
  helper-dialect: mysql
  reasonable: true
